export enum AllActionType {
  MSG = "MSG",
  MOVIES = "MOVIES",
  MOVIE_HOME_CARD = "MOVIE_HOME_CARD",
  MOVIE_SEARCH_CARD = "MOVIE_SEARCH_CARD",
  CLEAR_UP_MOVIES = "CLEAR_UP_MOVIES",
  MODAL = "MODAL",
  CLEAR_UP_MODAL = "CLEAR_UP_MODAL"
}
